name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: >
          Hello @${{ github.actor }}, thank you for submitting a PR! We will respond as soon as possible.
          
          Note that we are in the process of migraing to NetBeans 11 so all PR's should be sent to `master-nb11`.
          
        issue-message: >
          Hello @${{ github.actor }}, thank you for your interest in our work!
          
          If you have a question about using Constellation then please have a read of our [Quick Start Guide](https://github.com/constellation-app/constellation/raw/master/docs/Constellation_Quick_Start_Guide.pdf).
          
          If you are a developer then it is advised to go through the [Developer Training Guide](https://github.com/constellation-app/constellation-training). Note that we are in the process of migrating to NetBeans 11 but the training guide is still on NetBeans 8.2.
